### PR TITLE
added metadata fileInputPath and fileOutputPath

### PR DESCRIPTION
**Pull request by bashaus**
Hey there

I've had a use case where I want to know (1) what the name of the file is before transformation and (2) what the name of the file will be post-transformation

I've put this together, but I'm not sure what you'll think of it. It changes a lot of the existing code (but doesn't change the API).

Let me know what you think. I'm happy to take direction if you want to refactor it.

### CODE REVIEW

**Comment by ismay** [comment]
Hi @bashaus, thanks for the pr. I understand what you're trying to do, but I think that this isn't something that belongs in the engine. It would be a lot easier to create two small plugins that set `fileInputPath` or `fileOutputPath`.

```
Metalsmith(__dirname)
  .use(setFileInputPath)
  .use(inPlace)
  .use(setFileOutputPath)
  .build(function(err){
    if (err) throw err;
  });

function setFileInputPath(files, metalsmith, done){
  for (var file in files) {
    files[file].fileInputPath = file
  }

  done();
}

function setFileOutputPath(files, metalsmith, done){
  for (var file in files) {
    files[file].fileOutputPath = file
  }

  done();
}
```

That keeps this plugin focused and way more simple.

**Comment by bashaus** [comment]
No worries, I understand the need for simplicity. My question is this: how do you get the fileOutputPath while you're transforming from inplace?

**Comment by ismay** [comment]
> My question is this: how do you get the fileOutputPath while you're transforming from inplace?

I'm not sure if I understand what you're trying to do, but the metalsmith files object will be updated by metalsmith-in-place with the new filename. So:

```
{
  'index.html.hbs': {
    contents: ''
    mode: ''
    etc.
  }
  'someotherfile.html : {}
}
```

will become

```
{
  'index.html': {
    contents: ''
    mode: ''
    etc.
  }
  'someotherfile.html : {}
}
```

How it updates the filenames exactly depends on the jstransformers being applied.

**Comment by bashaus** [comment]
So the use case is, is I have a sore called sitemap.xml and I want to know the name is the destination path, rather than the source path, how do I get it?

Because if I look for page.path it would return (for example) index.html.njk instead of index.html

Or if I am building the canonical URL for a page, there's no metadata for the page destination path, only the template path

Let me know if this makes no sense and you need a code sample for a use case and I'll knock one up when I get in front of a computer

**Comment by ismay** [comment]
If you want to build a sitemap use [metalsmith-sitemap](https://github.com/ExtraHop/metalsmith-sitemap) and if you want to add a canonical url use [metalsmith-canonical](https://www.npmjs.com/package/metalsmith-canonical). And for support I'd try the metalsmith slack channel: https://metalsmith-slack.herokuapp.com/

**Comment by bashaus** [comment]
Didn't get a response on Slack, so posting this here:

`metalsmith.json`

```{
  "metalsmith-collections": {
    "portfolio_items": {
      "pattern": "portfolio/*/index.html.njk",
      "sortBy": "date",
      "reverse": true
    }
  },
  "metalsmith-in-place": true
}
```


`index.html.njk`

```<table>
  {% for work in portfolio_items %}
    <tr>
      <td><a href="{{ work.path }}">{{ work.title }}</a></td>
    </tr>
  {% endfor %}
</table>```

How would you achieve the following use-case?

**Pull request closed without merging**
